spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:9192
          predicates:
            - Path=/order/**
          filters:
           - AuthenticationFilter

        - id: payment-service
          uri: http://localhost:9191
          predicates:
            - Path=/payment/**
          filters:
           - AuthenticationFilter
           
        - id: authentication_service
          uri: http://localhost:9195
          predicates:
           - Path=/auth/**   
       
server: 
  port: 8989

eureka:
  client:
    service-url.defaultZone: http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    

        
#hysstrix:
 # command:
  #  fallbackcmd:
   #   execution:
    #    isolation:
     #     thread:
      #      timeoutInMilliseconds: 5000  
  

    
    
    
    